# Generated by Django 3.2.16 on 2023-05-17 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBodega', models.CharField(max_length=50)),
                ('direccionBodega', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('descripcionProducto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='productoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('id_Bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloApp.bodega')),
                ('id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloApp.producto')),
            ],
        ),
    ]
